jobs:
  build:
    docker:
      - image: <docker image>
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions: 'USERID1,USERID2'
          only_for_branches: only_for_branches
          webhook: SLACK_WEBHOOK
orbs:
  slack: circleci/slack@x.y.z
version: 2.1
