jobs:
  executor:
    name: node/default
  build:
    steps:
      - slack/notify:
          channel: CHANNELID
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: This is a custom message notification
          webhook: SLACK_WEBHOOK
orbs:
  slack: circleci/slack@3.4.2
version: 2.1
workflows:
  build:
    jobs:
      - build
