version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
      
    steps:
      - slack/notify:
          message: Starting E2E Tests
          mentions: 'channel'
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install typescript --save-dev
            - run: npm run build
            - run: npm run test | nl | sed  "1d;2d;3d" > test_results/tests.cucumber  
            - slack/status:
                success_message: ':tada: A $CIRCLE_JOB job has succeeded!'
                failure_message: ':red_circle: A $CIRCLE_JOB job has failed!'
                mentions: 'channel'
      - store_test_results:
              path: test_results
workflows:
    build-and-test:
      jobs:
        - build-and-test
